export type RouteArea = 'public' | 'central' | 'edge' | 'mobile' | 'exam-client';
export type RouteStatus = 'implemented' | 'placeholder' | 'service-endpoint' | 'reserved';

export interface RouteContract { path: string; label: string; area: RouteArea; roles: readonly string[]; status: RouteStatus; }

export const routeContracts = [
  { path: '/login', label: 'Login Pusat', area: 'public', roles: ['SUPER_ADMIN', 'CONTENT_ADMIN', 'REVIEWER'], status: 'placeholder' },
  { path: '/forgot-password', label: 'Lupa Password', area: 'public', roles: ['STAFF'], status: 'placeholder' },
  { path: '/health', label: 'Health Check', area: 'public', roles: [], status: 'service-endpoint' },
  { path: '/readiness', label: 'Readiness Check', area: 'public', roles: [], status: 'service-endpoint' },
  { path: '/dashboard', label: 'Overview Nasional', area: 'central', roles: ['SUPER_ADMIN', 'CONTENT_ADMIN'], status: 'placeholder' },
  { path: '/schools', label: 'Daftar Sekolah', area: 'central', roles: ['SUPER_ADMIN', 'SCHOOL_ADMIN'], status: 'implemented' },
  { path: '/schools/new', label: 'Tambah Sekolah', area: 'central', roles: ['SUPER_ADMIN'], status: 'placeholder' },
  { path: '/schools/:id', label: 'Detail Sekolah', area: 'central', roles: ['SUPER_ADMIN', 'SCHOOL_ADMIN'], status: 'placeholder' },
  { path: '/edges', label: 'Daftar Edge Device', area: 'central', roles: ['SUPER_ADMIN'], status: 'placeholder' },
  { path: '/edges/:id', label: 'Detail Edge', area: 'central', roles: ['SUPER_ADMIN'], status: 'placeholder' },
  { path: '/question-bank', label: 'Bank Soal', area: 'central', roles: ['CONTENT_ADMIN', 'REVIEWER'], status: 'placeholder' },
  { path: '/question-bank/prediction', label: 'Prediksi Soal', area: 'central', roles: ['CONTENT_ADMIN', 'REVIEWER'], status: 'implemented' },
  { path: '/question-bank/import', label: 'Import Soal', area: 'central', roles: ['CONTENT_ADMIN'], status: 'placeholder' },
  { path: '/question-bank/:id', label: 'Detail Soal', area: 'central', roles: ['CONTENT_ADMIN', 'REVIEWER'], status: 'placeholder' },
  { path: '/reviews', label: 'Review Soal', area: 'central', roles: ['REVIEWER'], status: 'placeholder' },
  { path: '/package-builder', label: 'Daftar Paket', area: 'central', roles: ['CONTENT_ADMIN'], status: 'placeholder' },
  { path: '/package-builder/new', label: 'Buat Paket', area: 'central', roles: ['CONTENT_ADMIN'], status: 'placeholder' },
  { path: '/package-builder/:id', label: 'Detail Paket', area: 'central', roles: ['CONTENT_ADMIN'], status: 'placeholder' },
  { path: '/distributions', label: 'Monitoring Distribusi', area: 'central', roles: ['SUPER_ADMIN', 'SCHOOL_ADMIN'], status: 'placeholder' },
  { path: '/schedules', label: 'Jadwal Ujian', area: 'central', roles: ['SUPER_ADMIN', 'SCHOOL_ADMIN'], status: 'placeholder' },
  { path: '/results', label: 'Rekap Hasil Nasional', area: 'central', roles: ['SUPER_ADMIN', 'SCHOOL_ADMIN', 'AUDITOR'], status: 'placeholder' },
  { path: '/sync-failures', label: 'Sinkronisasi Gagal', area: 'central', roles: ['SUPER_ADMIN', 'AUDITOR'], status: 'placeholder' },
  { path: '/audit-log', label: 'Audit Log', area: 'central', roles: ['SUPER_ADMIN', 'AUDITOR'], status: 'implemented' },
  { path: '/settings/ml', label: 'Pengaturan ML', area: 'central', roles: ['SUPER_ADMIN'], status: 'implemented' },
  { path: '/profile', label: 'Profil Admin', area: 'central', roles: ['STAFF'], status: 'placeholder' },
  { path: '/local/login', label: 'Login Operator', area: 'edge', roles: ['SCHOOL_ADMIN', 'SCHOOL_OPERATOR', 'PROCTOR'], status: 'placeholder' },
  { path: '/local/dashboard', label: 'Status Server Lokal', area: 'edge', roles: ['SCHOOL_ADMIN', 'SCHOOL_OPERATOR', 'PROCTOR'], status: 'implemented' },
  { path: '/local/network', label: 'Status LAN', area: 'edge', roles: ['SCHOOL_ADMIN', 'SCHOOL_OPERATOR'], status: 'implemented' },
  { path: '/local/packages', label: 'Paket Tersedia', area: 'edge', roles: ['SCHOOL_ADMIN', 'SCHOOL_OPERATOR'], status: 'implemented' },
  { path: '/local/schedules', label: 'Aktivasi Ujian', area: 'edge', roles: ['SCHOOL_ADMIN', 'SCHOOL_OPERATOR'], status: 'implemented' },
  { path: '/local/participants', label: 'Daftar Peserta', area: 'edge', roles: ['SCHOOL_ADMIN', 'SCHOOL_OPERATOR', 'PROCTOR'], status: 'implemented' },
  { path: '/local/monitor', label: 'Monitor Peserta', area: 'edge', roles: ['SCHOOL_ADMIN', 'SCHOOL_OPERATOR', 'PROCTOR'], status: 'implemented' },
  { path: '/local/sync', label: 'Sinkronisasi Hasil', area: 'edge', roles: ['SCHOOL_ADMIN', 'SCHOOL_OPERATOR'], status: 'implemented' },
  { path: '/local/storage', label: 'Kapasitas Storage', area: 'edge', roles: ['SCHOOL_ADMIN', 'SCHOOL_OPERATOR'], status: 'implemented' },
  { path: '/local/logs', label: 'Log Operasional', area: 'edge', roles: ['SCHOOL_ADMIN', 'AUDITOR'], status: 'implemented' },
  { path: '/local/notifications', label: 'Notifikasi Edge', area: 'edge', roles: ['SCHOOL_ADMIN', 'SCHOOL_OPERATOR', 'PROCTOR'], status: 'placeholder' },
  { path: '/local/settings', label: 'Pengaturan Edge', area: 'edge', roles: ['SCHOOL_ADMIN'], status: 'implemented' },
  { path: '/mobile/login', label: 'Login Mobile', area: 'mobile', roles: ['SCHOOL_OPERATOR'], status: 'implemented' },
  { path: '/mobile/dashboard', label: 'Dashboard Mobile', area: 'mobile', roles: ['SCHOOL_OPERATOR'], status: 'implemented' },
  { path: '/mobile/monitor', label: 'Monitor Mobile', area: 'mobile', roles: ['SCHOOL_OPERATOR'], status: 'implemented' },
  { path: '/mobile/notifications', label: 'Notifikasi Mobile', area: 'mobile', roles: ['SCHOOL_OPERATOR'], status: 'implemented' },
  { path: '/client', label: 'Launcher Peserta', area: 'exam-client', roles: ['STUDENT'], status: 'reserved' },
  { path: '/client/login', label: 'Login Peserta', area: 'exam-client', roles: ['STUDENT'], status: 'reserved' },
  { path: '/client/exam', label: 'Layar Ujian', area: 'exam-client', roles: ['STUDENT'], status: 'reserved' },
  { path: '/client/result', label: 'Skor Instan', area: 'exam-client', roles: ['STUDENT'], status: 'reserved' },
  { path: '/client/system-check', label: 'Pemeriksaan Perangkat', area: 'exam-client', roles: ['STUDENT'], status: 'reserved' },
  { path: '/client/reconnect', label: 'Pemulihan Sesi', area: 'exam-client', roles: ['STUDENT'], status: 'reserved' },
  { path: '/client/locked', label: 'Mode Ujian', area: 'exam-client', roles: ['STUDENT'], status: 'reserved' },
] as const satisfies readonly RouteContract[];

export function routesFor(area: RouteArea) { return routeContracts.filter((route) => route.area === area); }
